version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!@#Root123"
      # MYSQL_ROOT_HOST: "%"
      MYSQL_USER: user
      MYSQL_PASSWORD: "!@#User123"
      TZ: Asia/Seoul
    volumes:
      - /docker-data/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=4096
      - --general_log=1
      - --general_log_file=/var/lib/mysql/general.log
      - --log_error=/var/lib/mysql/error.log
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
#    networks:
#      - db-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - "21010:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    restart: always
#    networks:
#      - my-net
#      - db-net

#networks:
#  my-net:
#    external:
#      name: my-net
#  db-net:
#    driver: bridge

networks:
  default:
    external:
      name: my-net

# docker-compose -f dc-mysql.yml up -d
# docker-compose -f dc-mysql.yml down
