version: "3"

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "!@#Root123"
    volumes:
      - /docker-data/mongo:/data/db
    restart: always

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-ex
#    ports:
#      - "21030:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: "!@#Root123"
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: "!@#Admin123"
#    depends_on:
#      - mongo
#    restart: always

networks:
  default:
    external:
      name: my-net

# docker-compose -f dc-mongo.yml up -d
# docker-compose -f dc-mongo.yml down
