version: "3"

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /docker-data/redis:/data
    # command: redis-server --requirepass !@#Redis123 --port 6379
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-cmd
    ports:
      - "21020:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: "!@#Admin123"
    depends_on:
      - redis
    restart: always

networks:
  default:
    external:
      name: my-net

# docker-compose -f dc-redis.yml up -d
# docker-compose -f dc-redis.yml down
